{
 "title": "Metrics",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Deployment Frequency over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "columnId": "repository_id",
     "columnTime": "date",
     "columnValue": "frequency",
     "keyspace": "metrics",
     "table": "deployment_frequencies",
     "target": "SELECT grouping_key, adapter, date, frequency FROM metrics.deployment_frequencies WHERE date > $__timeFrom and date < $__timeTo ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Mean Deployment Frequency",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "columnId": "repository_id",
     "columnTime": "date",
     "columnValue": "frequency",
     "keyspace": "metrics",
     "table": "deployment_frequencies",
     "target": "SELECT grouping_key, adapter, date, AVG(frequency) FROM metrics.deployment_frequencies WHERE date > $__timeFrom and date < $__timeTo GROUP BY adapter, grouping_key ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Mean Lead Time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "columnId": "repository_id",
     "columnValue": "frequency",
     "keyspace": "metrics",
     "table": "deployment_frequencies",
     "target": "SELECT repository_id, adapter, AVG(lead_time_milliseconds) FROM metrics.lead_times WHERE lead_time_milliseconds > 0 GROUP BY adapter, repository_id ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Distinct Issues",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "SELECT repository_id, adapter, count(*) FROM metrics.lead_times GROUP BY adapter, repository_id ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Mean Times To Restore Service",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "SELECT repository_id, adapter, AVG(time_to_restore_service_milliseconds) FROM metrics.times_to_restore_service GROUP BY adapter, repository_id ALLOW FILTERING"
    }
   ]
  },
  {
   "title": "Mean Change Failure Rate",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "SELECT repository_id, adapter, AVG(rate) FROM metrics.change_failure_rates GROUP BY adapter, repository_id ALLOW FILTERING"
    }
   ]
  }
 ]
}